// Code generated by shimmy; DO NOT EDIT.

package main

import (
	"context"
	"shimmy"
)

type KVStoreShim struct {
	Inner      KVStore
	Middleware []KVStoreMiddleware
}

type KVStoreMiddleware interface {
	AroundGet(ctx context.Context, key string, next func(ctx context.Context, key string) (string, bool)) (string, bool)
	AroundSet(ctx context.Context, key string, value string, next func(ctx context.Context, key string, value string))
}

type BaseKVStoreMiddleware struct{}

func (b *BaseKVStoreMiddleware) AroundGet(ctx context.Context, key string, next func(ctx context.Context, key string) (string, bool)) (string, bool) {
	return next(ctx, key)
}

func (b *BaseKVStoreMiddleware) AroundSet(ctx context.Context, key string, value string, next func(ctx context.Context, key string, value string)) {
	next(ctx, key, value)
}

type GetCall struct {
	Ctx     context.Context
	Key     string
	Result1 string
	Result2 bool
}

func (c *GetCall) Method() string { return "Get" }
func (c *GetCall) Args() []any    { return []any{c.Ctx, c.Key} }
func (c *GetCall) Results() []any { return []any{c.Result1, c.Result2} }

type SetCall struct {
	Ctx   context.Context
	Key   string
	Value string
}

func (c *SetCall) Method() string { return "Set" }
func (c *SetCall) Args() []any    { return []any{c.Ctx, c.Key, c.Value} }
func (c *SetCall) Results() []any { return []any{} }

type kVStoreInterceptor struct {
	fn func(shimmy.Call, func())
}

func NewKVStoreInterceptor(fn func(shimmy.Call, func())) KVStoreMiddleware {
	return &kVStoreInterceptor{fn: fn}
}

func (i *kVStoreInterceptor) AroundGet(ctx context.Context, key string, next func(ctx context.Context, key string) (string, bool)) (string, bool) {
	call := &GetCall{Ctx: ctx, Key: key}
	invoke := func() {
		call.Result1, call.Result2 = next(call.Ctx, call.Key)
	}
	i.fn(call, invoke)
	return call.Result1, call.Result2
}

func (i *kVStoreInterceptor) AroundSet(ctx context.Context, key string, value string, next func(ctx context.Context, key string, value string)) {
	call := &SetCall{Ctx: ctx, Key: key, Value: value}
	invoke := func() {
		next(call.Ctx, call.Key, call.Value)
	}
	i.fn(call, invoke)
}

func (s *KVStoreShim) Get(ctx context.Context, key string) (string, bool) {
	var next func(ctx context.Context, key string) (string, bool)
	next = func(ctx context.Context, key string) (string, bool) {
		return s.Inner.Get(ctx, key)
	}
	for idx := len(s.Middleware) - 1; idx >= 0; idx-- {
		mw := s.Middleware[idx]
		prev := next
		next = func(ctx context.Context, key string) (string, bool) {
			return mw.AroundGet(ctx, key, prev)
		}
	}
	return next(ctx, key)
}

func (s *KVStoreShim) Set(ctx context.Context, key string, value string) {
	var next func(ctx context.Context, key string, value string)
	next = func(ctx context.Context, key string, value string) {
		s.Inner.Set(ctx, key, value)
	}
	for idx := len(s.Middleware) - 1; idx >= 0; idx-- {
		mw := s.Middleware[idx]
		prev := next
		next = func(ctx context.Context, key string, value string) {
			mw.AroundSet(ctx, key, value, prev)
		}
	}
	next(ctx, key, value)
}
