// Code generated by shimmy; DO NOT EDIT.

package main

import (
	"context"
	"shimmy"
)

type PaymentProcessorShim struct {
	Inner      PaymentProcessor
	Middleware []PaymentProcessorMiddleware
}

type PaymentProcessorMiddleware interface {
	AroundCharge(ctx context.Context, accountID string, cents int, next func(ctx context.Context, accountID string, cents int) (PaymentResult, error)) (PaymentResult, error)
}

type BasePaymentProcessorMiddleware struct{}

func (b *BasePaymentProcessorMiddleware) AroundCharge(ctx context.Context, accountID string, cents int, next func(ctx context.Context, accountID string, cents int) (PaymentResult, error)) (PaymentResult, error) {
	return next(ctx, accountID, cents)
}

type ChargeCall struct {
	Ctx       context.Context
	AccountID string
	Cents     int
	Result1   PaymentResult
	Result2   error
}

func (c *ChargeCall) Method() string { return "Charge" }
func (c *ChargeCall) Args() []any    { return []any{c.Ctx, c.AccountID, c.Cents} }
func (c *ChargeCall) Results() []any { return []any{c.Result1, c.Result2} }

type paymentProcessorInterceptor struct {
	fn func(shimmy.Call, func())
}

func NewPaymentProcessorInterceptor(fn func(shimmy.Call, func())) PaymentProcessorMiddleware {
	return &paymentProcessorInterceptor{fn: fn}
}

func (i *paymentProcessorInterceptor) AroundCharge(ctx context.Context, accountID string, cents int, next func(ctx context.Context, accountID string, cents int) (PaymentResult, error)) (PaymentResult, error) {
	call := &ChargeCall{Ctx: ctx, AccountID: accountID, Cents: cents}
	invoke := func() {
		call.Result1, call.Result2 = next(call.Ctx, call.AccountID, call.Cents)
	}
	i.fn(call, invoke)
	return call.Result1, call.Result2
}

func (s *PaymentProcessorShim) Charge(ctx context.Context, accountID string, cents int) (PaymentResult, error) {
	var next func(ctx context.Context, accountID string, cents int) (PaymentResult, error)
	next = func(ctx context.Context, accountID string, cents int) (PaymentResult, error) {
		return s.Inner.Charge(ctx, accountID, cents)
	}
	for idx := len(s.Middleware) - 1; idx >= 0; idx-- {
		mw := s.Middleware[idx]
		prev := next
		next = func(ctx context.Context, accountID string, cents int) (PaymentResult, error) {
			return mw.AroundCharge(ctx, accountID, cents, prev)
		}
	}
	return next(ctx, accountID, cents)
}
