package generator

import (
	"bytes"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/printer"
	"go/token"
	"path"
	"strconv"
	"strings"
)

type Method struct {
	Name    string
	Params  []Param
	Results []Param
}

type Param struct {
	Name       string
	Type       string
	IsVariadic bool

	CallField string
}

type Interface struct {
	PackageName string
	Name        string
	Methods     []Method
	Imports     []Import
}

type Import struct {
	Alias string
	Path  string
}

// ParseInterfaceFile parses a single Go source file and extracts one interface.
//
// limitations:
// - Embedded interfaces are not supported.
// - Generic interfaces are not supported.
func ParseInterfaceFile(filePath, interfaceName string) (Interface, error) {
	fset := token.NewFileSet()
	file, err := parser.ParseFile(fset, filePath, nil, parser.SkipObjectResolution)
	if err != nil {
		return Interface{}, fmt.Errorf("parse input file: %w", err)
	}

	ifSpec, err := findInterfaceSpec(file, interfaceName)
	if err != nil {
		return Interface{}, err
	}

	if ifSpec.TypeParams != nil && len(ifSpec.TypeParams.List) > 0 {
		return Interface{}, fmt.Errorf("interface %q has type parameters; generics are unsupported in v0", interfaceName)
	}

	ifaceType, ok := ifSpec.Type.(*ast.InterfaceType)
	if !ok {
		return Interface{}, fmt.Errorf("type %q exists but is not an interface", interfaceName)
	}

	methods, err := parseMethods(fset, ifaceType)
	if err != nil {
		return Interface{}, err
	}

	usedAliases := collectUsedImportAliases(ifaceType)
	imports := collectImports(file.Imports, usedAliases)

	return Interface{
		PackageName: file.Name.Name,
		Name:        interfaceName,
		Methods:     methods,
		Imports:     imports,
	}, nil
}

// Generate produces formatted Go code implementing shim artifacts for an interface.
func Generate(i Interface) ([]byte, error) {
	raw, err := generateRaw(i)
	if err != nil {
		return nil, err
	}

	fmtOut, err := format.Source(raw)
	if err != nil {
		return nil, fmt.Errorf("format generated code: %w\n\n%s", err, string(raw))
	}
	return fmtOut, nil
}

func GenerateFromFile(filePath, interfaceName string) ([]byte, error) {
	i, err := ParseInterfaceFile(filePath, interfaceName)
	if err != nil {
		return nil, err
	}
	return Generate(i)
}

func generateRaw(i Interface) ([]byte, error) {
	if len(i.Methods) == 0 {
		return nil, fmt.Errorf("interface %q has no methods", i.Name)
	}

	var b strings.Builder
	b.WriteString("// Code generated by shimmy; DO NOT EDIT.\n")
	b.WriteString("\n")
	b.WriteString("package ")
	b.WriteString(i.PackageName)
	b.WriteString("\n\n")

	imports := i.Imports
	needsShimmyImport := i.PackageName != "shimmy"
	if needsShimmyImport {
		imports = append(imports, Import{Path: "shimmy"})
	}

	if len(imports) > 0 {
		b.WriteString("import (\n")
		for _, imp := range imports {
			b.WriteString("\t")
			if imp.Alias != "" {
				b.WriteString(imp.Alias)
				b.WriteString(" ")
			}
			b.WriteString(strconv.Quote(imp.Path))
			b.WriteString("\n")
		}
		b.WriteString(")\n\n")
	}

	iface := i.Name
	shimName := iface + "Shim"
	mwName := iface + "Middleware"
	baseName := "Base" + iface + "Middleware"
	interceptorStructName := lowerFirst(iface) + "Interceptor"
	callType := "shimmy.Call"
	if !needsShimmyImport {
		callType = "Call"
	}

	// shim struct
	fmt.Fprintf(&b, "type %s struct {\n", shimName)
	fmt.Fprintf(&b, "\tInner %s\n", iface)
	fmt.Fprintf(&b, "\tMiddleware []%s\n", mwName)
	b.WriteString("}\n\n")

	// middleware interface
	fmt.Fprintf(&b, "type %s interface {\n", mwName)
	for _, m := range i.Methods {
		fmt.Fprintf(&b, "\tAround%s(%s) %s\n", m.Name, renderAroundParams(m), renderResultSignature(m.Results))
	}
	b.WriteString("}\n\n")

	// base middleware passthrough
	fmt.Fprintf(&b, "type %s struct{}\n\n", baseName)
	for _, m := range i.Methods {
		fmt.Fprintf(&b, "func (b *%s) Around%s(%s) %s {\n", baseName, m.Name, renderAroundParams(m), renderResultSignature(m.Results))
		callNext := renderCall("next", m.Params, true)
		if len(m.Results) == 0 {
			fmt.Fprintf(&b, "\t%s\n", callNext)
			b.WriteString("}\n\n")
		} else {
			fmt.Fprintf(&b, "\treturn %s\n", callNext)
			b.WriteString("}\n\n")
		}
	}

	// call envelopes
	for _, m := range i.Methods {
		callName := m.Name + "Call"
		fmt.Fprintf(&b, "type %s struct {\n", callName)
		for _, p := range m.Params {
			fmt.Fprintf(&b, "\t%s %s\n", p.CallField, paramFieldType(p))
		}
		for _, r := range m.Results {
			fmt.Fprintf(&b, "\t%s %s\n", r.CallField, r.Type)
		}
		b.WriteString("}\n\n")

		fmt.Fprintf(&b, "func (c *%s) Method() string { return %q }\n", callName, m.Name)
		fmt.Fprintf(&b, "func (c *%s) Args() []any { return []any{%s} }\n", callName, renderCallFieldList(m.Params))
		fmt.Fprintf(&b, "func (c *%s) Results() []any { return []any{%s} }\n\n", callName, renderCallFieldList(m.Results))
	}

	// interceptor constructor and type
	fmt.Fprintf(&b, "type %s struct {\n", interceptorStructName)
	fmt.Fprintf(&b, "\tfn func(%s, func())\n", callType)
	b.WriteString("}\n\n")
	fmt.Fprintf(&b, "func New%sInterceptor(fn func(%s, func())) %s {\n", iface, callType, mwName)
	fmt.Fprintf(&b, "\treturn &%s{fn: fn}\n", interceptorStructName)
	b.WriteString("}\n\n")

	for _, m := range i.Methods {
		fmt.Fprintf(&b, "func (i *%s) Around%s(%s) %s {\n", interceptorStructName, m.Name, renderAroundParams(m), renderResultSignature(m.Results))
		fmt.Fprintf(&b, "\tcall := &%sCall{%s}\n", m.Name, renderCallEnvelopeInit(m.Params))
		b.WriteString("\tinvoke := func() {\n")
		nextCall := renderCall("next", renderCallParams(m.Params), true)
		if len(m.Results) == 0 {
			fmt.Fprintf(&b, "\t\t%s\n", nextCall)
		} else {
			fmt.Fprintf(&b, "\t\t%s = %s\n", renderAssignmentLeft(m.Results, "call."), nextCall)
		}
		b.WriteString("\t}\n")
		b.WriteString("\ti.fn(call, invoke)\n")
		if len(m.Results) > 0 {
			fmt.Fprintf(&b, "\treturn %s\n", renderAssignmentLeft(m.Results, "call."))
		}
		b.WriteString("}\n\n")
	}

	// shim methods
	for _, m := range i.Methods {
		fmt.Fprintf(&b, "func (s *%s) %s(%s) %s {\n", shimName, m.Name, renderSignatureParams(m.Params), renderResultSignature(m.Results))
		nextType := fmt.Sprintf("func(%s) %s", renderSignatureParams(m.Params), renderResultSignature(m.Results))
		fmt.Fprintf(&b, "\tvar next %s\n", nextType)
		innerCall := renderCall("s.Inner."+m.Name, m.Params, true)
		if len(m.Results) == 0 {
			fmt.Fprintf(&b, "\tnext = func(%s) %s {\n", renderSignatureParams(m.Params), renderResultSignature(m.Results))
			fmt.Fprintf(&b, "\t\t%s\n", innerCall)
			b.WriteString("\t}\n")
		} else {
			fmt.Fprintf(&b, "\tnext = func(%s) %s {\n", renderSignatureParams(m.Params), renderResultSignature(m.Results))
			fmt.Fprintf(&b, "\t\treturn %s\n", innerCall)
			b.WriteString("\t}\n")
		}

		b.WriteString("\tfor idx := len(s.Middleware) - 1; idx >= 0; idx-- {\n")
		b.WriteString("\t\tmw := s.Middleware[idx]\n")
		b.WriteString("\t\tprev := next\n")
		fmt.Fprintf(&b, "\t\tnext = func(%s) %s {\n", renderSignatureParams(m.Params), renderResultSignature(m.Results))
		aroundCall := renderCall("mw.Around"+m.Name, append(copyParams(m.Params), Param{Name: "prev", Type: nextType}), false)
		if len(m.Results) == 0 {
			fmt.Fprintf(&b, "\t\t\t%s\n", aroundCall)
		} else {
			fmt.Fprintf(&b, "\t\t\treturn %s\n", aroundCall)
		}
		b.WriteString("\t\t}\n")
		b.WriteString("\t}\n")

		finalCall := renderCall("next", m.Params, true)
		if len(m.Results) == 0 {
			fmt.Fprintf(&b, "\t%s\n", finalCall)
		} else {
			fmt.Fprintf(&b, "\treturn %s\n", finalCall)
		}
		b.WriteString("}\n\n")
	}

	return []byte(b.String()), nil
}

func findInterfaceSpec(file *ast.File, interfaceName string) (*ast.TypeSpec, error) {
	for _, decl := range file.Decls {
		gen, ok := decl.(*ast.GenDecl)
		if !ok || gen.Tok != token.TYPE {
			continue
		}
		for _, spec := range gen.Specs {
			ts, ok := spec.(*ast.TypeSpec)
			if !ok || ts.Name.Name != interfaceName {
				continue
			}
			return ts, nil
		}
	}
	return nil, fmt.Errorf("unknown interface %q", interfaceName)
}

func parseMethods(fset *token.FileSet, iface *ast.InterfaceType) ([]Method, error) {
	methods := make([]Method, 0, len(iface.Methods.List))
	for _, field := range iface.Methods.List {
		if len(field.Names) == 0 {
			switch field.Type.(type) {
			case *ast.Ident, *ast.SelectorExpr:
				return nil, fmt.Errorf("embedded interfaces are unsupported in v0")
			default:
				return nil, fmt.Errorf("unsupported interface element in v0")
			}
		}
		if len(field.Names) != 1 {
			return nil, fmt.Errorf("unsupported interface element with %d names", len(field.Names))
		}

		ft, ok := field.Type.(*ast.FuncType)
		if !ok {
			return nil, fmt.Errorf("unsupported interface element %q: only methods are supported", field.Names[0].Name)
		}

		params, err := parseFieldList(fset, ft.Params, "arg")
		if err != nil {
			return nil, fmt.Errorf("method %s params: %w", field.Names[0].Name, err)
		}
		results, err := parseFieldList(fset, ft.Results, "result")
		if err != nil {
			return nil, fmt.Errorf("method %s results: %w", field.Names[0].Name, err)
		}
		assignCallFields(params, "Arg")
		assignCallFields(results, "Result")

		methods = append(methods, Method{
			Name:    field.Names[0].Name,
			Params:  params,
			Results: results,
		})
	}
	return methods, nil
}

func parseFieldList(fset *token.FileSet, list *ast.FieldList, fallbackPrefix string) ([]Param, error) {
	if list == nil || len(list.List) == 0 {
		return nil, nil
	}

	params := make([]Param, 0, len(list.List))
	fallbackIdx := 1
	for _, field := range list.List {
		t, isVariadic, err := exprString(fset, field.Type)
		if err != nil {
			return nil, err
		}

		if len(field.Names) == 0 {
			name := fmt.Sprintf("%s%d", fallbackPrefix, fallbackIdx)
			fallbackIdx++
			params = append(params, Param{Name: name, Type: t, IsVariadic: isVariadic})
			continue
		}

		for _, n := range field.Names {
			params = append(params, Param{Name: n.Name, Type: t, IsVariadic: isVariadic})
		}
	}

	return params, nil
}

func exprString(fset *token.FileSet, e ast.Expr) (string, bool, error) {
	isVariadic := false
	if ellipsis, ok := e.(*ast.Ellipsis); ok {
		isVariadic = true
		e = ellipsis.Elt
	}

	var buf bytes.Buffer
	if err := printer.Fprint(&buf, fset, e); err != nil {
		return "", false, err
	}

	if isVariadic {
		return "..." + buf.String(), true, nil
	}
	return buf.String(), false, nil
}

func collectUsedImportAliases(iface *ast.InterfaceType) map[string]struct{} {
	used := map[string]struct{}{}
	ast.Inspect(iface, func(n ast.Node) bool {
		sel, ok := n.(*ast.SelectorExpr)
		if !ok {
			return true
		}
		ident, ok := sel.X.(*ast.Ident)
		if !ok {
			return true
		}
		used[ident.Name] = struct{}{}
		return true
	})
	return used
}

func collectImports(specs []*ast.ImportSpec, usedAliases map[string]struct{}) []Import {
	imports := make([]Import, 0, len(specs))
	seen := map[string]struct{}{}
	for _, spec := range specs {
		pathValue, err := strconv.Unquote(spec.Path.Value)
		if err != nil {
			continue
		}

		alias := ""
		if spec.Name != nil {
			alias = spec.Name.Name
		}

		if alias == "_" {
			continue
		}

		effectiveAlias := alias
		if effectiveAlias == "" {
			effectiveAlias = path.Base(pathValue)
		}

		if alias == "." {
			if _, ok := seen[alias+"|"+pathValue]; ok {
				continue
			}
			imports = append(imports, Import{Alias: alias, Path: pathValue})
			seen[alias+"|"+pathValue] = struct{}{}
			continue
		}

		if _, ok := usedAliases[effectiveAlias]; !ok {
			continue
		}

		key := alias + "|" + pathValue
		if _, ok := seen[key]; ok {
			continue
		}
		imports = append(imports, Import{Alias: alias, Path: pathValue})
		seen[key] = struct{}{}
	}
	return imports
}

func assignCallFields(params []Param, prefix string) {
	used := map[string]int{}
	for idx := range params {
		base := toExportedName(params[idx].Name)
		if base == "" {
			base = fmt.Sprintf("%s%d", prefix, idx+1)
		}
		count := used[base]
		used[base] = count + 1
		if count > 0 {
			params[idx].CallField = fmt.Sprintf("%s%d", base, count+1)
		} else {
			params[idx].CallField = base
		}
	}
}

func toExportedName(name string) string {
	if name == "" {
		return ""
	}
	if name == "_" {
		return "Underscore"
	}
	runes := []rune(name)
	if runes[0] >= 'a' && runes[0] <= 'z' {
		runes[0] = runes[0] - ('a' - 'A')
	}
	return string(runes)
}

func lowerFirst(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	if r[0] >= 'A' && r[0] <= 'Z' {
		r[0] = r[0] + ('a' - 'A')
	}
	return string(r)
}

func renderAroundParams(m Method) string {
	parts := make([]string, 0, len(m.Params)+1)
	for _, p := range m.Params {
		parts = append(parts, renderAroundParamDecl(p))
	}
	nextType := fmt.Sprintf("func(%s) %s", renderSignatureParams(m.Params), renderResultSignature(m.Results))
	parts = append(parts, "next "+nextType)
	return strings.Join(parts, ", ")
}

func renderSignatureParams(params []Param) string {
	parts := make([]string, 0, len(params))
	for _, p := range params {
		parts = append(parts, renderParamDecl(p))
	}
	return strings.Join(parts, ", ")
}

func renderParamDecl(p Param) string {
	return p.Name + " " + p.Type
}

func renderAroundParamDecl(p Param) string {
	if p.IsVariadic {
		return p.Name + " " + variadicAsSliceType(p.Type)
	}
	return renderParamDecl(p)
}

func renderResultSignature(results []Param) string {
	if len(results) == 0 {
		return ""
	}
	parts := make([]string, 0, len(results))
	for _, r := range results {
		if r.Name == "" || strings.HasPrefix(r.Name, "result") {
			parts = append(parts, r.Type)
		} else {
			parts = append(parts, r.Name+" "+r.Type)
		}
	}
	if len(parts) == 1 {
		return parts[0]
	}
	return "(" + strings.Join(parts, ", ") + ")"
}

func renderCall(funcName string, params []Param, spreadVariadic bool) string {
	args := make([]string, 0, len(params))
	for _, p := range params {
		if p.IsVariadic && spreadVariadic {
			args = append(args, p.Name+"...")
		} else {
			args = append(args, p.Name)
		}
	}
	return fmt.Sprintf("%s(%s)", funcName, strings.Join(args, ", "))
}

func renderCallParams(params []Param) []Param {
	out := copyParams(params)
	for idx := range out {
		out[idx].Name = "call." + out[idx].CallField
	}
	return out
}

func copyParams(params []Param) []Param {
	out := make([]Param, len(params))
	copy(out, params)
	return out
}

func renderCallFieldList(params []Param) string {
	if len(params) == 0 {
		return ""
	}
	vals := make([]string, 0, len(params))
	for _, p := range params {
		vals = append(vals, "c."+p.CallField)
	}
	return strings.Join(vals, ", ")
}

func renderCallEnvelopeInit(params []Param) string {
	if len(params) == 0 {
		return ""
	}
	parts := make([]string, 0, len(params))
	for _, p := range params {
		parts = append(parts, p.CallField+": "+p.Name)
	}
	return strings.Join(parts, ", ")
}

func renderAssignmentLeft(params []Param, prefix string) string {
	parts := make([]string, 0, len(params))
	for _, p := range params {
		parts = append(parts, prefix+p.CallField)
	}
	return strings.Join(parts, ", ")
}

func paramFieldType(p Param) string {
	if p.IsVariadic {
		return variadicAsSliceType(p.Type)
	}
	return p.Type
}

func variadicAsSliceType(typ string) string {
	return "[]" + strings.TrimPrefix(typ, "...")
}
