// Code generated by shimmy; DO NOT EDIT.

package main

import (
	"context"
	"shimmy"
)

type UserServiceShim struct {
	Inner      UserService
	Middleware []UserServiceMiddleware
}

type UserServiceMiddleware interface {
	AroundGetUser(ctx context.Context, id string, next func(ctx context.Context, id string) (User, error)) (User, error)
	AroundCreateUser(ctx context.Context, id string, name string, next func(ctx context.Context, id string, name string) (User, error)) (User, error)
}

type BaseUserServiceMiddleware struct{}

func (b *BaseUserServiceMiddleware) AroundGetUser(ctx context.Context, id string, next func(ctx context.Context, id string) (User, error)) (User, error) {
	return next(ctx, id)
}

func (b *BaseUserServiceMiddleware) AroundCreateUser(ctx context.Context, id string, name string, next func(ctx context.Context, id string, name string) (User, error)) (User, error) {
	return next(ctx, id, name)
}

type GetUserCall struct {
	Ctx     context.Context
	Id      string
	Result1 User
	Result2 error
}

func (c *GetUserCall) Method() string { return "GetUser" }
func (c *GetUserCall) Args() []any    { return []any{c.Ctx, c.Id} }
func (c *GetUserCall) Results() []any { return []any{c.Result1, c.Result2} }

type CreateUserCall struct {
	Ctx     context.Context
	Id      string
	Name    string
	Result1 User
	Result2 error
}

func (c *CreateUserCall) Method() string { return "CreateUser" }
func (c *CreateUserCall) Args() []any    { return []any{c.Ctx, c.Id, c.Name} }
func (c *CreateUserCall) Results() []any { return []any{c.Result1, c.Result2} }

type userServiceInterceptor struct {
	fn func(shimmy.Call, func())
}

func NewUserServiceInterceptor(fn func(shimmy.Call, func())) UserServiceMiddleware {
	return &userServiceInterceptor{fn: fn}
}

func (i *userServiceInterceptor) AroundGetUser(ctx context.Context, id string, next func(ctx context.Context, id string) (User, error)) (User, error) {
	call := &GetUserCall{Ctx: ctx, Id: id}
	invoke := func() {
		call.Result1, call.Result2 = next(call.Ctx, call.Id)
	}
	i.fn(call, invoke)
	return call.Result1, call.Result2
}

func (i *userServiceInterceptor) AroundCreateUser(ctx context.Context, id string, name string, next func(ctx context.Context, id string, name string) (User, error)) (User, error) {
	call := &CreateUserCall{Ctx: ctx, Id: id, Name: name}
	invoke := func() {
		call.Result1, call.Result2 = next(call.Ctx, call.Id, call.Name)
	}
	i.fn(call, invoke)
	return call.Result1, call.Result2
}

func (s *UserServiceShim) GetUser(ctx context.Context, id string) (User, error) {
	var next func(ctx context.Context, id string) (User, error)
	next = func(ctx context.Context, id string) (User, error) {
		return s.Inner.GetUser(ctx, id)
	}
	for idx := len(s.Middleware) - 1; idx >= 0; idx-- {
		mw := s.Middleware[idx]
		prev := next
		next = func(ctx context.Context, id string) (User, error) {
			return mw.AroundGetUser(ctx, id, prev)
		}
	}
	return next(ctx, id)
}

func (s *UserServiceShim) CreateUser(ctx context.Context, id string, name string) (User, error) {
	var next func(ctx context.Context, id string, name string) (User, error)
	next = func(ctx context.Context, id string, name string) (User, error) {
		return s.Inner.CreateUser(ctx, id, name)
	}
	for idx := len(s.Middleware) - 1; idx >= 0; idx-- {
		mw := s.Middleware[idx]
		prev := next
		next = func(ctx context.Context, id string, name string) (User, error) {
			return mw.AroundCreateUser(ctx, id, name, prev)
		}
	}
	return next(ctx, id, name)
}
